#!/usr/bin/env pwsh
# open-pr.ps1 — 创建 PR（正文含 Closes #issue，语言按配置）
#
# 用法：
#   pwsh open-pr.ps1 -Title "feat: ..." -Issues "T001,T002" [-Base main] [-Language zh-CN] [-BodyFile <path>] [-Repo owner/repo]

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Title,
    [string]$Issues = "",
    [string]$Base = "main",
    [string]$Language = "zh-CN",
    [string]$BodyFile = "",
    [string]$Repo = "",
    [string]$GeneratorName = "speckit-implement-loop"
)

$ErrorActionPreference = "Stop"
. "$PSScriptRoot/common.ps1"

$repoRoot = Find-RepoRoot
if (-not $repoRoot) { Write-Err "ERROR: 未找到仓库根（缺少 .specify/）。"; exit 1 }
if (-not $Repo) { $Repo = Get-GitRemoteRepo $repoRoot }
if (-not $Repo) { Write-Err "ERROR: 无法从 git remote 推导 owner/repo，请用 -Repo 指定。"; exit 1 }

$issueNums = @()
if ($Issues) {
    $issueNums = @($Issues -split ',' | ForEach-Object {
            ($_ -replace '^#', '' -replace '^T', '').Trim()
        } | Where-Object { $_ -match '^\d+$' })
}
$closesLines = if ($issueNums.Count -gt 0) { ($issueNums | ForEach-Object { "Closes #$_" }) -join "`n" } else { "" }

if ($BodyFile) {
    if (-not (Test-Path -LiteralPath $BodyFile -PathType Leaf)) {
        Write-Err "ERROR: 正文文件不存在：$BodyFile"
        exit 1
    }
    $body = Get-Content -LiteralPath $BodyFile -Raw
} else {
    if ($Language -eq "en") {
        $body = @"
## Changes

- Tasks: $Issues
$closesLines
- Generated by $GeneratorName; awaiting human review.
"@
    } else {
        $body = @"
## 变更说明

- 任务：$Issues
$closesLines
- 生成方式：$GeneratorName，待人工审查。
"@
    }
}

$tmp = [System.IO.Path]::GetTempFileName()
[System.IO.File]::WriteAllText($tmp, $body, [System.Text.Encoding]::UTF8)
try {
    gh pr create --repo $Repo --base $Base --title $Title --body-file $tmp
    if ($LASTEXITCODE -ne 0) { Write-Err "ERROR: gh pr create 失败。"; exit 1 }
} finally {
    Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue
}

Write-Host "PR 已创建（$Repo，base=$Base），等待人工审查与合并。"
exit 0
