#!/usr/bin/env pwsh
# open-pr.ps1 — 创建 PR（正文自动包含已完成任务的 Closes #issue）
#
# 用法：
#   pwsh open-pr.ps1 -Title "feat: ..." [-TasksFile <tasks.md>] [-Issues "T001,T002"] `
#        [-Base main] [-Language zh-CN] [-BodyFile <path>] [-Repo owner/repo] [-DryRun]
#
# Closes 收集规则：
#   - -TasksFile 提供时，自动收集其中所有 [X] 任务，并通过 issue 标题映射真实 issue 号；
#   - -Issues 中的 "T###" 同样按标题映射；纯数字（123 或 #123）直接作为 issue 号；
#   - 映射不到的任务输出警告（不阻塞创建，人工可补）。
# 失败语义（防漏关 issue）：
#   - -TasksFile 不存在或不可读 → 退出 1，不创建 PR；
#   - -TasksFile 有效但没有已完成（[X]）任务 → 退出 1（除非 -AllowEmptyCloses）。

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Title,
    [string]$Issues = "",
    [string]$TasksFile = "",
    [string]$Base = "main",
    [string]$Language = "zh-CN",
    [string]$BodyFile = "",
    [string]$Repo = "",
    [string]$GeneratorName = "speckit-implement-loop",
    [string]$TitlePattern = "^T\d{3,}",
    [switch]$DryRun,
    [switch]$AllowEmptyCloses
)

$ErrorActionPreference = "Stop"
. "$PSScriptRoot/common.ps1"

$repoRoot = Find-RepoRoot
if (-not $repoRoot) { Write-Err "ERROR: 未找到仓库根（缺少 .specify/）。"; exit 1 }
if (-not $Repo) { $Repo = Get-GitRemoteRepo $repoRoot }
if (-not $Repo) { Write-Err "ERROR: 无法从 git remote 推导 owner/repo，请用 -Repo 指定。"; exit 1 }

# ---- 1. 收集任务 ID ----
$taskIds = @()
if ($TasksFile) {
    if (-not (Test-Path -LiteralPath $TasksFile -PathType Leaf)) {
        Write-Err "ERROR: tasks.md 不存在：$TasksFile（不会创建无 Closes 的 PR）。"
        exit 1
    }
    $taskIds += @(Get-TaskIdsFromTasksFile -TasksFile $TasksFile -CompletedOnly)
    if ($taskIds.Count -eq 0 -and -not $AllowEmptyCloses) {
        Write-Err "ERROR: tasks.md 中没有已完成（[X]）任务，将生成无 Closes 的 PR（正是漏关 issue 的根源）。"
        Write-Err "请确认调用时机；确需创建请加 -AllowEmptyCloses。"
        exit 1
    }
}
$directIssueNums = @()
if ($Issues) {
    foreach ($item in ($Issues -split ',')) {
        $item = $item.Trim()
        if ($item -match '^#?(\d+)$') {
            $directIssueNums += [int]$Matches[1]
        } elseif ($item -match '(T\d{3,})') {
            $taskIds += $Matches[1]
        }
    }
}
$taskIds = @($taskIds | Select-Object -Unique)

# ---- 2. 任务 ID → issue 号映射（需要 gh/网络） ----
$issueMap = @{}
if ($taskIds.Count -gt 0) {
    $issueMap = Get-TaskIssueMap -Repo $Repo -TitlePattern $TitlePattern
    if ($null -eq $issueMap) {
        Write-Err "ERROR: 无法拉取 issue 列表（gh api 失败）。请确认 gh 已登录且有网络，或改用 -Issues 纯数字方式。"
        exit 1
    }
}

$closesNums = @($directIssueNums)
$unmapped = @()
foreach ($id in $taskIds) {
    if ($issueMap.ContainsKey($id)) {
        $closesNums += $issueMap[$id]
    } else {
        $unmapped += $id
    }
}
$closesNums = @($closesNums | Sort-Object -Unique)
if ($unmapped.Count -gt 0) {
    Write-Host "WARN: 以下已完成任务未找到对应 issue（不阻塞创建，可人工补充 Closes）：$($unmapped -join ', ')"
}
$closesLines = if ($closesNums.Count -gt 0) { ($closesNums | ForEach-Object { "Closes #$_" }) -join "`n" } else { "" }

# ---- 3. 正文（Closes 块由 Set-ClosesBlock 管理：只替换标记区，保留人工 Closes 行） ----
if ($BodyFile) {
    if (-not (Test-Path -LiteralPath $BodyFile -PathType Leaf)) {
        Write-Err "ERROR: 正文文件不存在：$BodyFile"
        exit 1
    }
    $body = Get-Content -LiteralPath $BodyFile -Raw
} elseif ($Language -eq "en") {
    $body = @"
## Changes

- Tasks: $($taskIds -join ', ')
- Generated by $GeneratorName; awaiting human review.
"@
} else {
    $body = @"
## 变更说明

- 任务：$($taskIds -join ', ')
- 生成方式：$GeneratorName，待人工审查。
"@
}
# 注意：open-pr 不启用旧格式迁移——BodyFile 是人工正文，裸 Closes 行一律保留，
# 只在末尾追加标记区；旧格式迁移仅由 sync-pr-closes 对既有 PR 执行。
$body = Set-ClosesBlock -Body $body -ClosesLines $closesLines

# ---- 4. 创建（或 DryRun） ----
if ($DryRun) {
    Write-Host "== DryRun：将创建 PR =="
    Write-Host "repo: $Repo | base: $Base | title: $Title"
    Write-Host "closes: $($closesNums -join ', ')"
    Write-Host "---- body ----"
    Write-Host $body
    exit 0
}

$tmp = [System.IO.Path]::GetTempFileName()
[System.IO.File]::WriteAllText($tmp, $body, [System.Text.Encoding]::UTF8)
try {
    gh pr create --repo $Repo --base $Base --title $Title --body-file $tmp
    if ($LASTEXITCODE -ne 0) { Write-Err "ERROR: gh pr create 失败。"; exit 1 }
} finally {
    Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue
}

Write-Host "PR 已创建（$Repo，base=$Base），等待人工审查与合并。"
exit 0
